### ISSUE TITLE
Docker image on public available repository

### ISSUE THREAD

**Issue by ebarped** [tonsV2/kubewatcher#4]
Hi:

I want to try this project, but having the docker image uploaded only on github requires github credentials to pull the image.

Maybe can you upload it to docker hub, so everyone can pull the docker image in an easy way?

Thanks, this project seems very nice!

**Comment by tonsV2** [comment]
Hi,

Thanks for the interesting in my project.

I actually already use docker hub. You can find the repository [here](https://hub.docker.com/repository/docker/tons/kubewatcher).

The easiest way to test it would be using docker-compose. Assuming your kubectl credentials are in ~/.kube/config you can simple do `docker-compose up`.

Due to some changes I've made in version 1.7 the helm package need to be updated. Something I'll do tomorrow or the day after.

Please let me know if you have any questions.

**Comment by ebarped** [comment]
My bad, i didnt search deep enough on dockerhub.

Btw, that link is asking me to login, but i managed to access with this one: [link](https://hub.docker.com/r/tons/kubewatcher/tags?page=1&ordering=last_updated)

**Comment by tonsV2** [comment]
No worries! You're not supposed to search for such things :-)

I might move away from Docker Hub which is why I'm also building here. But it's in the early making.

Once again, please let me know if you have any issues and also, I'd appreciate any kind of feedback you might have.

**Comment by tonsV2** [comment]
@ebarped, I updated and released the Helm chart last night.

There are some notes on installing it [here](https://github.com/tonsV2/kubewatcher#install-1).

I'm using helmfile to manage the stack on my personal server. The values file for that can be found [here](https://github.com/tonsV2/nuc-stack/blob/master/values/prod/kubewatcher-values.gotmpl).

**Comment by ebarped** [comment]
Hi again!

I have tested it with Slack and works the way is intended, so everything is fine!

BTW, i have 2 suggestions:

- Adding the link to the docker hub repository to the Readme for better accesibility.
- Create a directory named deploy (for example) where you group all the deployment methods (docker-compose, helm...). In this sense, i have created some manifest files to deploy with kubectl (im not a big fan of helm). If you want, i can make a PR to include this files, so people that doesnt have helm can test it more easily in a kubernetes environment.

See u!

**Comment by tonsV2** [comment]
Hi @ebarped,

That's great! And your input is appreciated.

The first suggestion is simple and I've already updated the readme.

Regarding the second, I can certainly see the benefit of grouping all deployment methods under a common folder. However not having the Docker file and the docker-compose file in the root of the project does can lead to some issues. However I'd love to see those manifest files. Would that be possible?

**Comment by ebarped** [comment]
Hello again:

I opened a PR with the manifest files.

BTW, i was planning on suggest integration with slack through Incoming Webhooks, but i think that this case is addressed by #5 .

Cheers!

**Comment by tonsV2** [comment]
Hi @ebarped,

Sorry for my absence, I got a new primary client and had a lot to wrap up with my old clients.

I truly appreciate the effort you put in to this and the interest in the project. But I feel the files you suggest to add are very similar to the output of `helm template helm/`.

I already updated the readme with a link to Docker Hub and your suggestion about grouping all deployment methods under a common folder makes sense (assuming there are more than two). So if you have any more feedback please don't hold back, thanks.
